DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;
USE employee_db;

CREATE TABLE departments (
	name VARCHAR(50) NOT NULL UNIQUE,
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);

DROP TABLE roles;

CREATE TABLE roles (
	title VARCHAR(50) NOT NULL UNIQUE,
    salary DECIMAL(11,2) NOT NULL,
    department_id INT UNSIGNED NOT NULL,
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
);

CREATE TABLE employees (
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	role_id INT UNSIGNED NOT NULL,
	manager_id INT UNSIGNED,
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (manager_id) REFERENCES employees(id) ON DELETE SET NULL
);
